version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: bugreporter
      POSTGRES_USER: buguser
      POSTGRES_PASSWORD: bugpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U buguser -d bugreporter"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/bugreporter
      - JDBC_DATABASE_USERNAME=buguser
      - JDBC_DATABASE_PASSWORD=bugpassword
      - CORS_ALLOWED_ORIGINS=https://your-main-app.com,http://localhost:3000
      - PORT=8080
    ports:
      - "8080:8080"

  # Frontend (Optional - you can deploy this or use the components in your own app)
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8080/api
    depends_on:
      - backend

volumes:
  postgres_data: 